server:
  port: 8001
spring:
  application:
    name: mall-admin
  profiles:
    active: dev #默认为开发环境

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:cn/**/mapper/*.xml

# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间

